//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartHomeEntities : DbContext
    {
        public SmartHomeEntities()
            : base("name=SmartHomeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Automation_Rules> Automation_Rules { get; set; }
        public virtual DbSet<Device_Data> Device_Data { get; set; }
        public virtual DbSet<Device_Settings> Device_Settings { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Sensor_Data> Sensor_Data { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeAction> TypeAction { get; set; }
        public virtual DbSet<User_Preferences> User_Preferences { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersToDevices> UsersToDevices { get; set; }
    }
}
