//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersToDevices
    {
        public int id { get; set; }
        public int device_id { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual Users Users { get; set; }
    }
}
