//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automation_Rules
    {
        public int rule_id { get; set; }
        public string rule_name { get; set; }
        public int trigger_event_id { get; set; }
        public int action_device_id { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual Events Events { get; set; }
    }
}
