//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device_Settings
    {
        public int setting_id { get; set; }
        public int device_id { get; set; }
        public string setting_name { get; set; }
        public string setting_value { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Devices Devices { get; set; }
    }
}
